#ifndef _DEFINE_BASE_H_
#define _DEFINE_BASE_H_

enum FieldValues
{
	ODD_FIELD = 0,
	EVEN_FIELD,
	MAX_FIELD
};

enum DisplayFormatValues
{
	DISPLAY_FORMAT_UYVY = 0,
	DISPLAY_FORMAT_YUY2,
	MAX_DISPLAY_FORMAT
};
#define DEFAULT_DISPLAY_FORMAT	DISPLAY_FORMAT_YUY2

enum DataFormatValues
{
	DATAFORMAT_YUY422PK = 0,	
	DATAFORMAT_YUY411PL,
	DATAFORMAT_YUY420PL,
	MAX_DATA_FORMAT
};
#define DEFAULT_DATA_FORMAT		DATAFORMAT_YUY422PK

enum DataFieldValues
{
	DATAFIELD_ODD = 0,	
	DATAFIELD_EVEN,
	DATAFIELD_ALLFIELD,
	MAX_FIELD_FORMAT
};
#define DEFAULT_FIELD_FORMAT	DATAFIELD_EVEN

enum VideoForamtValues
{	
	VIDEO_FORMAT_NTSC = 0,
	VIDEO_FORMAT_PAL,
	MAX_VIDEO_FORMAT
};
#define DEFAULT_VIDEO_FORMAT	VIDEO_FORMAT_PAL

enum ImageSizeValues
{
	IMAGE_360X240 =	0,
	IMAGE_720X240,
	IMAGE_720X480,
	MAX_IMAGESIZE
};

enum VideoSizeValues
{
	Video_360X240 =	0,
	Video_180X120,
	Video_90X60,
	MAX_VIDEOSIZE
};

enum HScaleValues
{	
	HPIXEL_640_MODE = 0,
	HPIXEL_704_MODE,	
	HPIXEL_720_MODE,	
	MAX_HSCALE
};
#define DEFAULT_HSIZE_MODE		HPIXEL_704_MODE

enum ImageWidthValues
{
	IMAGEWIDTH_320_360 = 0,
	IMAGEWIDTH_640_720,
	MAX_IMAGEWIDTH
};

enum ImageHeightValues
{
	IMAGEHEIGHT_480 = 0,
	IMAGEHEIGHT_576,
	MAX_IMAGEHEIGHT
};
#define DEFAULT_IMAGE_HEIGHT	IMAGEHEIGHT_576

enum ImageWidthRValues
{
	IMAGEWIDTH_R320 = 320,
	IMAGEWIDTH_R352 = 352,
	IMAGEWIDTH_R360 = 360,
	IMAGEWIDTH_R640 = 640,
	IMAGEWIDTH_R704 = 704,
	IMAGEWIDTH_R720 = 720
};

enum ImageHeightRValues
{
	IMAGEHEIGHT_R480 = 480,
	IMAGEHEIGHT_R576 = 576
};

enum AudioBitsPerSample
{
	AUDIO_8BIT_SAMPLE =	0,
	AUDIO_16BIT_SAMPLE,
	MAX_BITSPER_SAMPLE
};
#define DEFAULT_AUDIO_SAMPLE	AUDIO_16BIT_SAMPLE

enum DisplayModeValues
{
	DISPLAY_MODE_1	= 0,	
	DISPLAY_MODE_4,
	MAX_DISPLAY_MODE
};
#define DEFAULT_DISPLAY_MODE	DISPLAY_MODE_4	//

enum AudioSamplingFrquency
{
	AUDIO_FRQ_8 =	0,	
	AUDIO_FRQ_16,
	MAX_AUDIO_FRQ,
};
#define DEFAULT_AUDIO_FRQ		AUDIO_FRQ_16

//Device
#define MAX_VIDEO_CHANNEL			4
#define MAX_AUDIO_CHANNEL			8

#define MAX_CHANNEL_CHANGEABLE		30
#define INVALID_CHANNEL_NUMBER		0xFF

#define MAX_DECODER					4

#define DMA_VIDEO_RECORD			2
#define DMA_AUDIO_RECORD			4

#define MEM_LOCK					1
#define MEM_UNLOCK					0

#define PAGESIZE					4096
#define MAX_VIDEO_QUEUE				8
#define MAX_AUDIO_QUEUE				8

#define MAX_VIDEO_CAP_SIZE			103*MAX_VIDEO_QUEUE			// 720*288*2/PAGESIZE*MAX_VIDEO_QUEUE
#define MAX_ENCODER_SIZE			20							// 720*288*2/PAGESIZE/5(max compression rate)
#define MAX_AUDIO_CAP_SIZE			17*MAX_AUDIO_QUEUE			// 16KHz*2Byte*8channel/4(0.25sec)/4096(pagesize)

#define CUR_AUDIO_PACKET_LENGTH		8000						// 250ms,  2*16,000=32,000 -> 1s
#define AUDIO_ONE_QUEUE_SIZE		8*CUR_AUDIO_PACKET_LENGTH

#define R_DEVICE_NAME				"\\\\.\\NVP1204%d"
#define MAX_DEVICE_NAME				0x80

#define MAX_ONE_CHANNEL_FPS_NTSC	30
#define MAX_ONE_CHANNEL_FPS_PAL		25

#define VIDEO_CAPTURE				1
#define DX_OFFSCREEN				0

#define WINDOW_WIDTH				1024
#define WINDOW_HEIGHT				750

#define LOGO_WIDTH					320
#define LOGO_HEIGHT					240
#define OVERLAY_START_LEFT			18
#define OVERLAY_START_TOP			12

#define MAX_PATH_SIZE				512

#define NVP1204_WINDOW_NAME			"NEXTCHIP WinDlg Window"
#define NVP1204_EXE_NAME			"NVP1204.exe"
#define LOGO_FILE_NAME				"Logo_320X240.bmp"


//Color Control
#define MAX_COLOR					4
#define COLOR_BRIGHTNESS			0
#define COLOR_CONTRAST				1
#define COLOR_COLOR					2
#define COLOR_HUE					3
#define COLOR_ALL					0xFF

#define BK_OVERLAY_COLORKEY_32		(RGB(130, 130, 130))
#define BK_CAPTURE_COLORKEY_32		(RGB( 30,  30,  30))
#define LINE_RECT_COLOR				(RGB(240, 248, 255))
#define FOCUS_RECT_COLOR			(RGB( 50,  50, 200))
#define VSYNC_LOSS_COLORKEY			(RGB(220,  20,  60))

enum SystemLanguageID
{
	ID_KOREAN   = 0x412,
	ID_ENGLISH  = 0x409,
	ID_JAPANESE = 0x411
};

#endif

